language: python
jobs:
  include:
    - os: linux
      python: 2.7
    - os: linux
      python: 3.6
    - os: linux
      python: 3.7
    - os: linux
      python: 3.8
    - os: linux
      python: nightly
    - os: linux
      python: pypy
    - os: linux
      python: pypy3
    - os: osx
      osx_image: xcode12
      language: generic
    - os: windows
      language: generic
      before_install:
        - choco install python --version 3.6.0
        - python -m pip install --upgrade pip
      env: PATH=/c/Python36:/c/Python36/Scripts:$PATH
    - os: windows
      language: generic
      before_install:
        - choco install python --version 3.8.0
        - python -m pip install --upgrade pip
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH
script: python -m pytest
