#!/bin/sh
GVF="$1"
DEF_VER="1.1.0rc1"
SED="${SED-sed}"
LF='
'
# First see if there is a version file (included in release tarballs),
# then try git-describe, then default.
if test -f version ; then
	VN=$(cat version) || VN="$DEF_VER"
elif test -d .git -o -f .git &&
	VN=$(git describe --match "v[0-9]*" --abbrev=4 HEAD 2>/dev/null) &&
	case "$VN" in
	*$LF*) (exit 1) ;;
	[0-9]*)
		git update-index -q --refresh
		test -z "$(git diff-index --name-only HEAD --)" ||
		VN="$VN-dirty" ;;
	esac
then
	VN=$(echo "$VN" | $SED 's/-/./g')
else
	VN="$DEF_VER"
fi
VN=$(expr "$VN" : v*'\(.*\)')
if test -r "$GVF" ; then
	VC=$($SED 's/^VERSION = //' < "$GVF")
else
	VC=unset
fi
if test "$VN" != "$VC" ; then
	echo "VERSION = $VN" >&2
	echo "VERSION = $VN" > "$GVF"
	echo "set(VERSION \"$VN\")" > "$GVF".cmake
fi
